### ISSUE TITLE
Ugly plots

### ISSUE THREAD

**Issue by roysiu-gh** [roysiu-gh/DDPM-HL-LHC#5]
Happens on wide cropped plots
May be fixed with Delta R
E.g. look at jet 13, crop 0.9

**Comment by chpxu** [comment]
Delta R can help but a Delta R of 1 is still fairly large image. Perhaps we need a different visualisation or modify the circles in a way that makes them visible.

Make the outer circles too large and it creates mayhem and makes it hard to see where the particles are.

Make the circles too small and it's just hard to see anything except the most energetic particles. Depends what we want
